name: Update gist with Steam Playtime

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
    

jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
          UPDATE_OPTION: MARKDOWN
          MARKDOWN_FILE: README.md
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 8a5f1c6573cfe601f14b84e2af89d2f9
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Run Steam-box and pusb
      run: |-
        go run ./cmd/box/main.go
        git config --global user.email "bot@github.com" && git config --global user.name "Steam-Bot"
        git diff
        git add README.md && git commit -m ":memo: update profile" || exit 0
        git pull && git push
